<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Car;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // First truncate the cars table to start fresh
        DB::table('cars')->truncate();
        
        // Sample car data based on frontend/src/assets/assets.js
        $cars = [
            [
                'name' => 'Mercedes-Benz S-Class',
                'brand' => 'Mercedes-Benz',
                'model' => 'S-Class',
                'year' => '2023',
                'daily_rate' => 350,
                'description' => 'Experience ultimate luxury with the Mercedes-Benz S-Class, featuring premium leather interior, advanced driver assistance systems, and unparalleled comfort.',
                'category' => 'luxury',
                'color' => 'Silver',
                'transmission' => '9-Speed Automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'MB-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Rolls-Royce Boat Tail',
                'brand' => 'Rolls-Royce',
                'model' => 'Boat Tail',
                'year' => '2023',
                'daily_rate' => 320,
                'description' => 'Dominate the road with the Rolls-Royce Boat Tail, delivering exhilarating performance with its twin-turbo inline-six engine and race-inspired handling.',
                'category' => 'luxury',
                'color' => 'Blue',
                'transmission' => '8-Speed Automatic',
                'seats' => 4,
                'doors' => 2,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'RR-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Audi A8 L',
                'brand' => 'Audi',
                'model' => 'A8 L',
                'year' => '2023',
                'daily_rate' => 380,
                'description' => 'The Audi A8 L represents the pinnacle of luxury with its adaptive air suspension, handcrafted interior, and cutting-edge technology for a refined driving experience.',
                'category' => 'luxury',
                'color' => 'Black',
                'transmission' => '8-Speed Automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'AU-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Porsche 911 Carrera',
                'brand' => 'Porsche',
                'model' => '911 Carrera',
                'year' => '2023',
                'daily_rate' => 390,
                'description' => 'The iconic Porsche 911 Carrera combines timeless design with exceptional performance, featuring precision handling and blistering acceleration.',
                'category' => 'sport',
                'color' => 'Red',
                'transmission' => '8-Speed PDK Automatic',
                'seats' => 4,
                'doors' => 2,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'PO-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Range Rover Sport',
                'brand' => 'Land Rover',
                'model' => 'Range Rover Sport',
                'year' => '2023',
                'daily_rate' => 320,
                'description' => 'Perfect for both city streets and off-road adventures, the Range Rover Sport offers luxury, comfort, and impressive all-terrain capabilities.',
                'category' => 'suv',
                'color' => 'Green',
                'transmission' => '8-Speed Automatic',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Diesel',
                'license_plate' => 'RR-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Lexus LC 500',
                'brand' => 'Lexus',
                'model' => 'LC 500',
                'year' => '2023',
                'daily_rate' => 350,
                'description' => 'The Lexus LC 500 combines breathtaking design with exhilarating performance, featuring a naturally aspirated V8 engine and luxurious interior appointments.',
                'category' => 'sport',
                'color' => 'White',
                'transmission' => '10-Speed Automatic',
                'seats' => 4,
                'doors' => 2,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'LE-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Bentley Continental GT',
                'brand' => 'Bentley',
                'model' => 'Continental GT',
                'year' => '2023',
                'daily_rate' => 600,
                'description' => 'Experience the pinnacle of grand touring with the Bentley Continental GT, featuring handcrafted materials, unmatched comfort, and breathtaking performance.',
                'category' => 'luxury',
                'color' => 'Black',
                'transmission' => '8-Speed Automatic',
                'seats' => 4,
                'doors' => 2,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'BE-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'BMW X7',
                'brand' => 'BMW',
                'model' => 'X7',
                'year' => '2023',
                'daily_rate' => 280,
                'description' => 'The BMW X7 offers first-class comfort with three rows of seating, cutting-edge technology, and robust performance for the ultimate family SUV experience.',
                'category' => 'suv',
                'color' => 'Blue',
                'transmission' => '8-Speed Automatic',
                'seats' => 7,
                'doors' => 5,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Diesel',
                'license_plate' => 'BM-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Tesla Model S Plaid',
                'brand' => 'Tesla',
                'model' => 'Model S Plaid',
                'year' => '2023',
                'daily_rate' => 450,
                'description' => 'Experience the future of driving with the Tesla Model S Plaid, featuring instant acceleration, long electric range, and cutting-edge autonomous driving technology.',
                'category' => 'luxury',
                'color' => 'White',
                'transmission' => 'Single-Speed',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Electric',
                'license_plate' => 'TS-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Lamborghini Urus',
                'brand' => 'Lamborghini',
                'model' => 'Urus',
                'year' => '2023',
                'daily_rate' => 550,
                'description' => 'The Lamborghini Urus is the world\'s first Super Sport Utility Vehicle, combining supercar performance with the versatility and practicality of an SUV.',
                'category' => 'suv',
                'color' => 'Yellow',
                'transmission' => '8-Speed Automatic',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'LM-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Ferrari Roma',
                'brand' => 'Ferrari',
                'model' => 'Roma',
                'year' => '2023',
                'daily_rate' => 650,
                'description' => 'The Ferrari Roma embodies \'La Nuova Dolce Vita\' with its timeless design and thrilling performance, delivering an authentic Ferrari grand touring experience.',
                'category' => 'sport',
                'color' => 'Red',
                'transmission' => '8-Speed Dual-Clutch',
                'seats' => 4,
                'doors' => 2,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'FR-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Cadillac Escalade',
                'brand' => 'Cadillac',
                'model' => 'Escalade',
                'year' => '2023',
                'daily_rate' => 300,
                'description' => 'The Cadillac Escalade sets the standard for luxury SUVs with its imposing presence, cutting-edge technology, and refined comfort for up to seven passengers.',
                'category' => 'suv',
                'color' => 'Black',
                'transmission' => '10-Speed Automatic',
                'seats' => 7,
                'doors' => 5,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'CD-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'McLaren 720S',
                'brand' => 'McLaren',
                'model' => '720S',
                'year' => '2023',
                'daily_rate' => 700,
                'description' => 'The McLaren 720S delivers breathtaking performance with its lightweight carbon fiber construction and twin-turbocharged V8 engine for a pure supercar experience.',
                'category' => 'sport',
                'color' => 'Orange',
                'transmission' => '7-Speed Dual-Clutch',
                'seats' => 2,
                'doors' => 2,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'MC-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Aston Martin DBX',
                'brand' => 'Aston Martin',
                'model' => 'DBX',
                'year' => '2023',
                'daily_rate' => 480,
                'description' => 'The Aston Martin DBX combines the soul of a sports car with the versatility of an SUV, featuring exquisite craftsmanship and exhilarating performance.',
                'category' => 'suv',
                'color' => 'Green',
                'transmission' => '9-Speed Automatic',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'AM-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Rolls-Royce Ghost',
                'brand' => 'Rolls-Royce',
                'model' => 'Ghost',
                'year' => '2023',
                'daily_rate' => 750,
                'description' => 'The Rolls-Royce Ghost delivers effortless luxury with its whisper-quiet cabin, hand-crafted materials, and innovative \'Planar Suspension System\' for the smoothest ride imaginable.',
                'category' => 'luxury',
                'color' => 'Silver',
                'transmission' => '8-Speed Automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'RG-' . Str::random(5),
                'is_available' => true,
            ],
            [
                'name' => 'Maserati Quattroporte',
                'brand' => 'Maserati',
                'model' => 'Quattroporte',
                'year' => '2023',
                'daily_rate' => 420,
                'description' => 'The Maserati Quattroporte combines Italian elegance with racing-bred performance, featuring a Ferrari-built twin-turbo V8 and hand-stitched luxury interior.',
                'category' => 'luxury',
                'color' => 'Blue',
                'transmission' => '8-Speed Automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'gps' => true,
                'bluetooth' => true,
                'usb' => true,
                'fuel_type' => 'Gasoline',
                'license_plate' => 'MS-' . Str::random(5),
                'is_available' => true,
            ],
        ];

        // Insert cars into database, checking for duplicates first
        foreach ($cars as $carData) {
            // Check if a car with the same name and brand already exists
            $existingCar = Car::where('name', $carData['name'])
                ->where('brand', $carData['brand'])
                ->first();
            
            if (!$existingCar) {
                Car::create($carData);
            }
        }
    }
} 